### PR TITLE
fix(Text): `_getFontDeclaration`

### LINKED ISSUE #9010: Text style bug?
https://github.com/fabricjs/fabric.js/blob/8536cb6149337ac30443d3931b648f136a85dea1/src/shapes/Text/Text.ts#L1609-L1629

Is this a bug?

```diff

- family = this.fontFamily, 
+ family = style.fontFamily, 

```

@asturur ?

### PR DESCRIPTION
**Pull request by ShaMan123**
## Motivation
closes #9010
closes #9041

## Description

The function **_getFontDeclaration** was suppose to take the font information from either the style object or the instance itself, but for fontFamily there is a bug in which the fontFamily is only taken from the instance.

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
fixed

**Review by ShaMan123 — COMMENTED** [review]
done

**Review by asturur — APPROVED** [review]

File: src/shapes/Text/Text.ts [hunk 1]
```diff
@@ -1640,25 +1641,31 @@ export class Text<
...
-        ? style.fontFamily
-        : `"${style.fontFamily}"`;
+    const parsedFontFamily =
+      fontFamily.includes("'") ||
+      fontFamily.includes('"') ||
+      fontFamily.includes(',') ||
+      Text.genericFonts.includes(fontFamily.toLowerCase())
+        ? fontFamily
+        : `"${fontFamily}"`;
     return [
```
Comment (jiayihu) [inline src/shapes/Text/Text.ts:1664]: Is this a hot path method? (e.g. called when rendering) In that case you should check if a string interpolation `${fontStyle} ${fontWeight} etc.` is significantly less expensive than creating an array on the fly and doing `join`

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 ## [next]
 
+- fix(Text): `_getFontDeclaration` [#9082](https://github.com/fabricjs/fabric.js/pull/9082)
```
Comment (jiayihu) [inline CHANGELOG.md:5]: This changelog doesn't tell much about the change. It should be more `_getFontDeclaration: passed style should take precedence` as the test case.

File: src/shapes/Text/Text.ts (hunk 1 above)
Comment (ShaMan123) [reply src/shapes/Text/Text.ts:1664]: I thought we should do that. It is called more than once in rendering

File: CHANGELOG.md (hunk 2 above)
Comment (ShaMan123) [reply CHANGELOG.md:5]: point noted

Comment (asturur) [reply CHANGELOG.md:5]: Yeah i also changed the pr description and the merge commit, but forgot to update the changelog.

**Comment by asturur** [comment]
Just for the record:

```js
_getFontDeclaration() {
    let {
      fontFamily = this.fontFamily,
      fontStyle = this.fontStyle,
      fontWeight = this.fontWeight,
      fontSize = this.fontSize
    } = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    let forMeasuring = arguments.length > 1 ? arguments[1] : undefined;
    const parsedFontFamily = fontFamily.includes("'") || fontFamily.includes('"') || fontFamily.includes(',') || Text.genericFonts.includes(fontFamily.toLowerCase()) ? fontFamily : "\"".concat(fontFamily, "\"");
    return [fontStyle, fontWeight, "".concat(forMeasuring ? this.CACHE_FONT_SIZE : fontSize, "px"), parsedFontFamily].join(' ');
  }
```

This is how the code gets transpiled so far.
template string become concats and the optional argument becomes horrible chain of argumentss keyword.

**Comment by asturur** [comment]
Seems like no browser supports optional arguments correctly, unless you ask babel to support only chrome 100 onward. that seems very strange to me.
