### PR TITLE
ci(): fix the coverage comment action

### LINKED ISSUE #10897: Fix the coverage action
The coverage action is broken since long.
It needs to be fixed.

It needs to reliably post coverage and possibly coverage on changed files.

### PR DESCRIPTION
**Pull request by asturur**
Fixes coverage artifact/comment workflow reliability.

Changes:
- Upload `coverage-vitest` and `coverage-e2e` artifacts with `if: always()`.
- Add `actions: read` permission to `.github/workflows/comment_coverage.yml`.
- Fix `prnumber` artifact read path in `.github/workflows/comment_coverage.yml`.
- update all the actions for upload/download to newer version on node 24 ( remove deprecation message of node 20 )

close #10897

### CODE REVIEW

**Comment by asturur** [comment]
Ok now the action runs OK, but the nyc coverage command fails, i solved the glaring bugs, now the actual one.

File: e2e/setup/setupCoverage.ts [hunk 1]
```diff
@@ -26,7 +26,8 @@ export async function stopCoverage(page: Page, outputDir: string) {
           });
           await converter.load();
           converter.applyCoverage(functions);
-          return [pathTo, converter.toIstanbul()];
+          const istanbul = converter.toIstanbul();
+          return Object.entries(istanbul)[0];
```
Comment (asturur) [inline e2e/setup/setupCoverage.ts:30]: this i could have lost hours, i was told by codex looking at my coverage files the issue is here. We have custom wrapping of coverage objects with an extra key and that was breaking it. At some point it was working decently, i wonder what happened

Comment (Smrtnyk) [reply e2e/setup/setupCoverage.ts:30]: maybe something in underlying api changed over newer versions

Comment (asturur) [reply e2e/setup/setupCoverage.ts:30]: maybe we changed coverage reporter.

**Comment by asturur** [comment]
I have to merge it in good faith because i can't run the modified action in a PR if the action runs as a workflow.
