### PR TITLE
various small svg fixes

### LINKED ISSUE #5412: SVG group loading failing
## Version
Kitchen Sink

## Test Case
On Kitchen Sink demo, use the following vector code:

    <?xml version="1.0" encoding="iso-8859-1"?>
    
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve">
    <circle style="fill:#7986CB;" cx="24" cy="24" r="20"/>
    <image style="display:none;overflow:visible;opacity:0.34;" width="87" height="79" xlink:href="8EB19EB6.jpg" transform="matrix(0.6329 0 0 0.6329 -4.0633 -0.5)">
    </image>
    <polygon style="fill:#E8EAF6;" points="31,17 24,14 17,17 14,24 17,31 24,34 31,31 34,24 "/>
    <polygon style="fill:#F3F5FF;" points="31,17 24,14 17,17 14,24 17,31 "/>
    <path style="fill:#C5CAE9;" d="M32.515,5.923C29.929,4.703,27.05,4,24,4v5L32.515,5.923z"/>
    <path style="fill:#F3F5FF;" d="M15.485,5.923C18.071,4.703,20.95,4,24,4v5L15.485,5.923z"/>
    <polygon style="fill:#C5CAE9;" points="14,14 24,14 17,17 "/>
    <polygon style="fill:#9FA8DA;" points="14,24 14,14 17,17 "/>
    <polygon style="fill:#C5CAE9;" points="15.485,5.923 14,14 24,9 "/>
    <polygon style="fill:#F3F5FF;" points="14,14 24,9 24,14 "/>
    <polygon style="fill:#F3F5FF;" points="14,24 9,24 14,14 "/>
    <polygon style="fill:#C5CAE9;" points="9,24 14,14 5.595,16.167 "/>
    <path style="fill:#F3F5FF;" d="M14,14L9.858,9.858c-1.797,1.797-3.252,3.936-4.263,6.309L14,14z"/>
    <path style="fill:#9FA8DA;" d="M9.858,9.858L14,14l1.485-8.076C13.387,6.913,11.478,8.237,9.858,9.858z"/>
    <path style="fill:#9FA8DA;" d="M5.595,16.167C4.57,18.573,4,21.219,4,24h5L5.595,16.167z"/>
    <path style="fill:#F3F5FF;" d="M5.923,32.515C4.703,29.929,4,27.05,4,24h5L5.923,32.515z"/>
    <polygon style="fill:#9FA8DA;" points="14,34 14,24 17,31 "/>
    <polygon style="fill:#C5CAE9;" points="24,34 14,34 17,31 "/>
    <polygon style="fill:#9FA8DA;" points="5.923,32.515 14,34 9,24 "/>
    <polygon style="fill:#C5CAE9;" points="14,34 9,24 14,24 "/>
    <polygon style="fill:#C5CAE9;" points="24,39 14,34 16.167,42.405 "/>
    <path style="fill:#9FA8DA;" d="M14,34l-4.142,4.142c1.797,1.797,3.936,3.252,6.309,4.263L14,34z"/>
    <path style="fill:#C5CAE9;" d="M9.858,38.142L14,34l-8.076-1.485C6.913,34.613,8.237,36.522,9.858,38.142z"/>
    <polygon style="fill:#9FA8DA;" points="34,14 24,14 31,17 "/>
    <polygon style="fill:#C5CAE9;" points="34,24 34,14 31,17 "/>
    <polygon style="fill:#E8EAF6;" points="32.515,5.923 34,14 24,9 "/>
    <polygon style="fill:#C5CAE9;" points="34,14 24,9 24,14 "/>
    <polygon style="fill:#9FA8DA;" points="34,24 39,24 34,14 "/>
    <path style="fill:#C5CAE9;" d="M34,14l4.142-4.142c1.797,1.797,3.252,3.936,4.263,6.309L34,14z"/>
    <path style="fill:#9FA8DA;" d="M38.142,9.858L34,14l-1.485-8.076C34.613,6.913,36.522,8.237,38.142,9.858z"/>
    <path style="fill:#9FA8DA;" d="M42.405,16.167C43.43,18.573,44,21.219,44,24h-5L42.405,16.167z"/>
    <polygon style="fill:#C5CAE9;" points="34,34 34,24 31,31 "/>
    <polygon style="fill:#9FA8DA;" points="42.077,32.515 34,34 39,24 "/>
    <polygon style="fill:#9FA8DA;" points="24,34 24,39 34,34 "/>
    <path style="fill:#9FA8DA;" d="M34,34l4.142,4.142c-1.797,1.797-3.936,3.252-6.309,4.263L34,34z"/>
    <path style="fill:#9FA8DA;" d="M31.833,42.405C29.427,43.43,26.781,44,24,44v-5L31.833,42.405z"/>
    </svg>

## Information about environment
Chrome Browser

## Steps to reproduce
Copy and paste the above vector code into the Kitchen Sink demo (loading a vector).

## Expected Behavior
It works.

## Actual Behavior
It doesn't, and produces this error in the console:

### LINKED ISSUE #5414: canvas.clipPath creates invalid SVG file
## Version
2.4.4

## Test Case
https://jsfiddle.net/jester1983/Da7SP/3171/

## Information about environment
chrome

## Steps to reproduce
create canvas, apply clipPath to canvas, toSVG the canvas

## Expected Behavior
clipPath path element has one transform attribute

## Actual Behavior
2 transform attributes, strict svg parsers fail

```
<clipPath id="CLIPPATH_1" >
	<path transform="matrix(2 0 0 1 201 150.5) translate(-150, -150)" d="M 100 100 v 100 h 100 V 100 H 100 z" stroke-linecap="round" transform=" translate(-150, -150)" />
</clipPath>
```

circle (and presumably other objects) are correct:
```
<clipPath id="CLIPPATH_3" >
	<circle transform="matrix(1 0 0 1 150.5 100.5)" cx="0" cy="0" r="100" />
</clipPath>
```

### LINKED ISSUE #5415: canvas.clipPath doesn't clip background in SVG
## Version
2.4.4

## Test Case
https://jsfiddle.net/jester1983/Da7SP/3172/

## Information about environment
chrome

## Steps to reproduce
create clipPath, then canvas.toSVG()

## Expected Behavior
canvas background is clipped

## Actual Behavior
background is not clipped.

suggest reorder steps for toSVG:

```
toSVG: function(options, reviver) {
      options || (options = { });
      options.reviver = reviver;
      var markup = [];

      this._setSVGPreamble(markup, options);
      this._setSVGHeader(markup, options);

      this._setSVGBgOverlayColor(markup, 'backgroundColor');
      this._setSVGBgOverlayImage(markup, 'backgroundImage', reviver);
      if (this.clipPath) {
        markup.push('<g clip-path="url(#' + this.clipPath.clipPathId + ')" >\n');
      }
      this._setSVGObjects(markup, reviver);
      if (this.clipPath) {
        markup.push('</g>\n');
      }
      this._setSVGBgOverlayColor(markup, 'overlayColor');
      this._setSVGBgOverlayImage(markup, 'overlayImage', reviver);

      markup.push('</svg>');

      return markup.join('');
    },
```
 should be 
```
toSVG: function(options, reviver) {
      options || (options = { });
      options.reviver = reviver;
      var markup = [];

      this._setSVGPreamble(markup, options);
      this._setSVGHeader(markup, options);

     
      if (this.clipPath) {
        markup.push('<g clip-path="url(#' + this.clipPath.clipPathId + ')" >\n');
      }
 this._setSVGBgOverlayColor(markup, 'backgroundColor');
      this._setSVGBgOverlayImage(markup, 'backgroundImage', reviver);
      this._setSVGObjects(markup, reviver);
      if (this.clipPath) {
        markup.push('</g>\n');
      }
      this._setSVGBgOverlayColor(markup, 'overlayColor');
      this._setSVGBgOverlayImage(markup, 'overlayImage', reviver);

      markup.push('</svg>');

      return markup.join('');
    },
```

or include overlays, not sure if overlay images should be clipped, but background definitely should be.

### LINKED ISSUE #5417: loadSVGFromString issue with letter-spacing
**Version**
2.3.0 & 2.4.4

**Test Case**
https://jsfiddle.net/rikkarv/98mc60ow/8/ (for version 2.3.0)
https://jsfiddle.net/rikkarv/98mc60ow/7/ (for version 2.4.4)

**Information about environment**
chrome

**Steps to reproduce**
click on svg's (outline with dashed blue) and see output in fabric (outline with dashed red)

**Expected Behavior**
svg text should be imported to canvas with correct letter-spacing, despite the letter-spacing unit

**Actual Behavior**
If (fabric version 2.3.0) {
  svg using letter-spacing value as "0.5em" works perfectly and outputs correct object.charSpacing value (500);
  svg using letter-spacing value as "10" doesn't work and outputs a wrong object.charSpacing value (625);
} else if (fabric version 2.3.0) {
  svg using letter-spacing value as "0.5em" doesn't work and outputs a wrong object.charSpacing value (0.5em);
  svg using letter-spacing value as "10" doesn't work and outputs a wrong object.charSpacing value (10);
}

### PR DESCRIPTION
**Pull request by asturur**
close #5412
close #5414 
close #5415 
close #5417

### CODE REVIEW

File: src/parser.js [hunk 1]
```diff
@@ -843,8 +844,10 @@
       ownAttributes = extend(ownAttributes,
         extend(getGlobalStylesForElement(element, svgUid), fabric.parseStyleAttribute(element)));
 
-      fontSize = (parentAttributes && parentAttributes.fontSize ) ||
-                   ownAttributes['font-size'] || fabric.Text.DEFAULT_SVG_FONT_SIZE;
+      fontSize = parentFontSize = parentAttributes.fontSize || fabric.Text.DEFAULT_SVG_FONT_SIZE;
+      if (ownAttributes['font-size']) {
+        fontSize = parseUnit(ownAttributes['font-size'], parentFontSize);
+      }
```
Comment (asturur) [inline src/parser.js]: @rikkarv the idea here is that 
- parseUnit should be used always.
- if the current fontSize is specified in EM ( i think is sort of legit ) we must reference the parent fontsize

Comment (asturur) [reply src/parser.js]: ok this is not good needs additional tweaking as per the uploaded test.
