### PR TITLE
types(): Make event type explicit - non generic, and fix pattern fromObject type

### LINKED ISSUE #9900: [Bug]: CanvasEvents["object:modified"] type has incorrect properties
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-rc1

### In What environments are you experiencing the problem?

_No response_

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-xs7c9w?workspaceId=1d1df649-1361-4e7f-b676-3d1aa87c1970

### Steps To Reproduce

1. Add "object:modified" event listener and use CanvasEvents["object:modified"] as a type

### Expected Behavior

To include the `e` property of TPointerEvent type just like `object:moving` type does. 

### Actual Behavior

The `e` property is passed to the callback, just the type is incorrect.

### Error Message & Stack Trace

```bash
`Property 'e' does not exist on type 'ModifiedEvent<TPointerEvent> | { target: FabricObject<Partial<FabricObjectProps>, SerializedObjectProps, ObjectEvents>; }'.`
```

### LINKED ISSUE #9906: SerializedPatternOptions type - union instead of intersection
### Discussed in https://github.com/fabricjs/fabric.js/discussions/9903

<div type='discussions-op-text'>

<sup>Originally posted by **owlcode** June  2, 2024</sup>
Looking at `SerializedPatternOptions` type [here](https://github.com/fabricjs/fabric.js/blob/1025c81c1d91e22df0c93ad3daea99d94e4435f0/src/Pattern/types.ts#L17C13-L17C37). Shouldn't it be union instead of intersection? Currently when I'm trying to do 
```
Pattern.fromObject(
      {
        type: 'pattern',
        source:
          'data:image/png;base64,iVBORw0KGgoAAAANSU....',
      },
      {},
    )
```
typescript is complaining that `source` needs to be of type `CanvasImageSource`. I'm using `6.0.0-rc1`</div>

### PR DESCRIPTION
**Pull request by asturur**
## Description

Just type fixes.
closes #9900
closes #9906

### CODE REVIEW

File: src/EventTypeDefs.ts [hunk 1]
```diff
@@ -106,28 +106,30 @@ export type TModificationEvents =
...
+
+type CanvasModificationEvents = {
   'before:transform': TEvent & { transform: Transform };
+  'object:moving': BasicTransformEvent & { target: FabricObject };
+  'object:scaling': BasicTransformEvent & { target: FabricObject };
+  'object:rotating': BasicTransformEvent & { target: FabricObject };
+  'object:skewing': BasicTransformEvent & { target: FabricObject };
+  'object:resizing': BasicTransformEvent & { target: FabricObject };
+  'object:modifyPoly': BasicTransformEvent & { target: FabricObject };
+  'object:modified': ModifiedEvent;
```
Comment (asturur) [inline src/EventTypeDefs.ts:132]: for me those types are more readable than the previous one. helps me keeping them in check.

Comment (jiayihu) [reply src/EventTypeDefs.ts:132]: Definitely better
