### PR TITLE
fix(serialization): restore explict class type

### LINKED ISSUE #9006: Minification breaks classRegistry
When using the minified version of fabricJS, the class registry looks like this:

image

This is wrong and comes from the fact that we are relying on constructor name to handle the label.

it should look like this

image

### LINKED ISSUE #9008: Minification breaks serialization
Currently serialization is broken.
While serialization and deserialization may work in the same app on the same build o fabricJS, there is no guarantee it will work across different builds.

Currenty when exporting an object we assign as type the name of the minified variable of the class:

image

That name is not stable and won't work across differnt builds.

Serialization in the current state is broken

### PR DESCRIPTION
**Pull request by asturur**
## Motivation

During the migration to "modern js" we thought that having a `type` property on an instance was kind of a duplicate because classes have costructor.name that is basically what type was.

Dumbly enough we didn't think that minification would have changed variable names and so constructor.name.
This wasn't caught by tests since tests run on the non minified version of the code.

This PR aims at fixing:
#9006 and #9008 making #9007 obsolete.

It restores class type, as a static property that will take the place o constructor.name ( constructor.type ).
The compatibility getter for type on the instances is still there and will return the static type.

closes #9006 
closes #9008

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
Looks good

File: test/unit/object.js [hunk 1]
```diff
@@ -293,7 +293,7 @@
 
   QUnit.test('toString', function (assert) {
     class Moo extends fabric.Object {
-      static type = 'moo'
+      static type = 'Moo'
```
Comment (asturur) [inline test/unit/object.js:296]: NO IDEA why this class already had a static type and what was testing.

File: src/filters/ColorMatrixFilters.ts [hunk 2]
```diff
@@ -7,6 +7,8 @@ export function createColorMatrixFilter(key: string, matrix: number[]) {
       return key;
     }
```
Comment (ShaMan123) [inline src/filters/ColorMatrixFilters.ts:8]: should be removed, extending ColorMatrix is enough

File: src/shapes/Object/Object.ts [hunk 3]
```diff
@@ -1454,7 +1463,10 @@ export class FabricObject<
    * @return {Boolean}
    */
   isType(...types: string[]) {
```
Comment (ShaMan123) [inline src/shapes/Object/Object.ts:1465]: should we deprecate this also??

**Review by ShaMan123 — COMMENTED** [review]
This looks good.
This will also solve my Bug since we disconnected class name and type (but I still think my PRs are valid but they an wait now).
I significant comment and another one for discussion

**Comment by CaptEmulation** [comment]
don't we need to update `ClassRegistry.ts` as well to use `.type`?

**Comment by asturur** [comment]
> don't we need to update `ClassRegistry.ts` as well to use `.type`?

i think i did it? i m sure i did it. Let me double check.

**Comment by asturur** [comment]
@CaptEmulation 
image

Is because tabs designs sucks.
We need vertical tabs since most of the screens are now 16:9.

At this point i need a test.

**Comment by asturur** [comment]
@ShaMan123  we verified this unblock my teammates at work.
So please for us is good, give it a review, and if there are no hiccups  i ll try to publish this tomorrow at the first occasion.

File: src/shapes/Object/Object.ts (hunk 3 above)
Comment (asturur) [reply src/shapes/Object/Object.ts:1465]: not part of this PR.
isType is not directly related to the incident. nor `isType` is wrong per se.

File: src/filters/ColorMatrixFilters.ts (hunk 2 above)
Comment (asturur) [reply src/filters/ColorMatrixFilters.ts:8]: those had their own name before, will keep them.
I m not even sure is possible with the different defualts. Without their type class they would serialize to ColorMatrix and then to the next deserialize wouldn't work anymore

**Comment by ShaMan123** [comment]
> > don't we need to update `ClassRegistry.ts` as well to use `.type`?
> 
> i think i did it? i m sure i did it. Let me double check.

How did tests pass then?

**Review by ShaMan123 — DISMISSED** [review]
I understand now what happened with tests.
Good

File: src/filters/ColorMatrixFilters.ts (hunk 2 above)
Comment (ShaMan123) [reply src/filters/ColorMatrixFilters.ts:8]: I want this removed because I think in the future it is a potential bug
Once we remove type getter this thing will become an artifact

Comment (ShaMan123) [reply src/filters/ColorMatrixFilters.ts:8]: > I m not even sure is possible with the different defualts

??
